# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ğŸ˜­å¤§é»„æˆ‘é”™äº†, åˆ«ç”Ÿæ°”å•¦ ~ # ex. I m Chuan
name: è¿™æ˜¯ä¸€å°é“æ­‰ä¿¡ ğŸ’Œ # ex. DONGChuan
email: my_email_address@lalala.com
location: Xian, China # ex. Nice, France
company: Rui â¤ Li
company_url: my_company_website
github_url: my_github_url # ex. https://github.com/DONGChuan
github_username: # ex. DONGChuan
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
repository: github_username/github_username.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://kiarma.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: ä¸»é¡µ

#  -
#    href: /open-source
#    label: å¼€æºé¡¹ç›®

  -
    href: /blog
    label: åšå®¢

  -
    href: /bookmark
    label: ä¹¦ç­¾

#  -
#    href: /about
#    label: å…³äº

# Sidebar to show popular repo
side_bar_repo_limit: 3 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
